
# By default, you MUST run `make build` first before running `docker-compose up`
# Passing in `--build` or just simply running `docker-compose up` is not sufficient to
# build the container. See [ASR-3118](https://jira.corp.adobe.com/browse/ASR-3118) for more details.
version: '3.7'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - ENVIRONMENT_NAME=local
     - REGION_NAME=local
