
# By default, you MUST run `make build` first before running `docker-compose up`
# Passing in `--build` or just simply running `docker-compose up` is not sufficient to
version: '2'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - ENVIRONMENT_NAME=local
     - REGION_NAME=local
